name: spb
description: "Secure Flutter application with comprehensive features"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/smart_logo.png"


dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.8
  go_router: ^14.2.7
  flutter_bloc: ^8.1.6
  
  # State Management & Architecture
  bloc: ^8.1.4
  equatable: ^2.0.5
  get_it: ^7.7.0
  injectable: ^2.4.4
  
  # HTTP & API
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  
  # Local Storage
  sqflite: ^2.3.3+1
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  path: ^1.9.1
  
  # Authentication & Security
  jwt_decoder: ^2.0.1
  crypto: ^3.0.5
  
  # QR Code
  qr_flutter: ^4.1.0
  image_gallery_saver_plus: ^4.0.1
  path_provider: ^2.1.4
  share_plus: ^7.2.2
  
  # File Operations
  file_picker: ^8.1.2
  image_picker: ^1.1.2
  image: ^4.2.0
  
  # PDF & Export
  pdf: ^3.11.1
  csv: ^6.0.0
  
  # Networking & Sync
  connectivity_plus: ^6.1.4
  
  # Utils
  intl: ^0.19.0
  logger: ^2.5.0
  uuid: ^4.5.1
  
  # UI Enhancements
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  
  # Permissions
  permission_handler: ^11.3.1
  dartz: ^0.10.1
  flutter_launcher_icons: ^0.14.4
  
  # Location
  geolocator: ^11.0.0
  
  # Analytics & Monitoring
  #firebase_core: ^3.6.0
  #firebase_crashlytics: ^4.1.3
  #firebase_analytics: ^11.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  retrofit_generator: ^8.2.1
  json_serializable: ^6.8.0
  
  # Testing
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    # - assets/images/
    - assets/icon/smart_logo.png
    # - assets/translations/
    - .env
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700